swagger: '2.0'
info:
  title: Authentication Without Passwd
  version: '1.0'
basePath: "/api"

paths:
  /name/{username}:
    get:
      operationId: services.get_name
      tags:
        - "Username"
      summary: "Get Hello"
      description: "<URL>/name/{user}"
      parameters:
        - name: username
          in: path
          type: string
          required: true
      responses:
        '200':
          description: OK
      security:
        - apiKey: []
  /token/{username}:
    get:
      operationId: security.basic_auth
      tags:
        - "Username"
      summary: "Get Hello"
      description: "<URL>/token/{user}"
      parameters:
        - name: username
          in: path
          type: string
          required: true
      responses:
        '200':
          description: OK
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-Auth
    x-apikeyInfoFunc: security.apikey_auth